# Generated by Django 5.1.3 on 2024-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctor_alter_patient_medical_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=150)),
            ],
        ),
    ]
