# Generated by Django 5.1.3 on 2024-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('admission_date', models.CharField(max_length=100)),
                ('discharge_date', models.CharField(max_length=100)),
                ('room_charge', models.CharField(max_length=100)),
                ('doctor_fee', models.CharField(max_length=100)),
                ('medicine_cost', models.CharField(max_length=100)),
                ('other_charge', models.CharField(max_length=100)),
            ],
        ),
    ]
