# Generated by Django 5.1.3 on 2024-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='doctor_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='medicine_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='other_charge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='room_charge',
            field=models.IntegerField(),
        ),
    ]
