# Generated by Django 5.1.3 on 2024-12-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_payment_doctor_fee_alter_payment_medicine_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_Name',
            new_name='patient_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discharge_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
