# Generated by Django 5.1.3 on 2024-12-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_appointment_date_alter_payment_admission_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='date1',
        ),
    ]
